### ISSUE TITLE
subdirectory "static" not installed by pip

### ISSUE THREAD

**Issue by jhgoebbert** [cmd-ntrf/jupyter-lmod#10]
Hi,

when I use "pip install jupyterlmod" through easybuild to install the module, the "static" directory is not copied to "/lib/python3.6/site-packages/jupyterlmod".
When then trying to install the jupyter extension with
" jupyter nbextension install jupyterlmod" it complains, that the files in "static/" are not found.

It seems to me, that subdirectories are not copied by "pip install" by default:
https://stackoverflow.com/questions/43253701/python-packaging-subdirectories-not-installed

Best,
Jens Henrik

**Comment by jhgoebbert** [comment]
A solution how to solve that is to use "package_date" in setup.py:
https://docs.python.org/3/distutils/setupscript.html#installing-package-data
like it is done here
https://github.com/jupyterlab/jupyterlab-latex/blob/master/setup.py

**Comment by jhgoebbert** [comment]
... another option might be to change this line:
https://github.com/cmd-ntrf/jupyter-lmod/blob/master/jupyterlab/tsconfig.json#L18
to point to the path where setup.py has copied lmod.js

**Comment by cmd-ntrf** [comment]
Hi Jens,

Sorry for the late reply, for some reason I was not subscribed to the issue of my own repo...

The `jupyter nbextension install` is no longer required. The files from static are now installed with the `data_files` option in setup.py.
https://github.com/cmd-ntrf/jupyter-lmod/blob/master/setup.py#L29

**Comment by jhgoebbert** [comment]
Thanks for answer.
Does that respect if the jupyter paths ( "jupyter --paths") are different from the python paths?

**Comment by cmd-ntrf** [comment]
I have only installed jupyter-lmod inside virtual environment where both jupyter and python paths are equivalent, so I can't really say.

**Comment by jhgoebbert** [comment]
The ability to set jupyter´s paths with special jupyter environment variables results in a high flexibility for systems where each software package has its own module. We have for example Python modules and an extra Jupyter module for itself. Therefore we must ensure, that Jupyter extensions do not install into paths, which are part of the Python module. I am not sure, if the use of data_files in setup.py is the "correct" jupyter-way of installing stuff.

But this is just a little remark - no big issue - your plugin is for us of real great help for us.
Big thanks again!!

**Comment by cmd-ntrf** [comment]
> I am not sure, if the use of data_files in setup.py is the "correct" jupyter-way of installing stuff.
It is slowly being adopted as the right way to install extensions. I have actually copied the method from Jupyter team's extensions like [jupyter-server-proxy ](https://github.com/jupyterhub/jupyter-server-proxy).

There a is bit of background and explanation on why using data_files in this PR:
https://github.com/jupyter/notebook/pull/3116

**Comment by jhgoebbert** [comment]
Thanks for the background and explanation - that is convincing.
I am sorry for wasting your time and close the issue.

**Comment by jhgoebbert** [comment]
We have already discussed this issue, but I would like to let you know, that we are still having trouble with the installation of jupyterlab-lmod and need to patch it before installation.

Because the subdirectory `static` is missing `jupyter labextension install jupyterlab-lmod` fails with
```Installing <..>Python-3.6.8/lib/python3.6/site-packages/jupyterlmod/static -> jupyterlmod
Traceback (most recent call last):
[..]
  File "<..>Python-3.6.8/lib/python3.6/site-packages/notebook/nbextensions.py", line 1014, in _should_copy
    if os.stat(src).st_mtime - os.stat(dest).st_mtime > 1e-6:
FileNotFoundError: [Errno 2] No such file or directory: '<..>Python-3.6.8/lib/python3.6/site-packages/jupyterlmod/static'
 (at easybuild/tools/run.py:533 in parse_cmd_output)
```

My solution is to patch `setup.py` and add `package_data={'jupyterlmod':['static/*']},`
We do not have this issue with any other extension we use (including jupyter-server-proxy).
