### ISSUE TITLE
jupyterlab 2.x

### ISSUE THREAD

**Issue by jhgoebbert** [cmd-ntrf/jupyter-lmod#13]
This is a fantastic module and we use it at Juelich Supercomputing Centre in all our JupyterLabs.
Currently it does not support JupyterLab 2.x, yet. By any chance, do you have plans to update jupyter-lmod to the new api 2.x?

**Comment by cmd-ntrf** [comment]
Wow thank you!

I somehow completely missed JupyterLab 2 release. I will look this week how to update to 2.0.

**Comment by jhgoebbert** [comment]
That would be great. Thanks a lot!

**Comment by cmd-ntrf** [comment]
The changes appear to be minimal, should be a quick fix.

That said, jupyter-lmod in its current form works with JupyterLab 2.x. I have not seen the release, but our setup was updated to 2.1.0 and the plugin still work. Did you face any particular issue when trying to load or use the module?

**Comment by jhgoebbert** [comment]
I saw `phosphor` in your code  
https://github.com/cmd-ntrf/jupyter-lmod/blob/master/jupyterlab/src/index.ts#L11

So I did not try.

**Comment by cmd-ntrf** [comment]
Done in commit : fb8c0b8e02c44593f6b13001a48441b209e3a7dc

I took the opportunity to do a small makeover of the collection action buttons that were broken. The package is now available on npm as jupyterlab-lmod 0.3.0.
https://www.npmjs.com/package/jupyterlab-lmod

Thanks again for the feedback!

**Comment by jhgoebbert** [comment]
Great! Thank you!  
I will try it out right away in our test-environment for JuypterLab 2.1

**Comment by jhgoebbert** [comment]
I tested it and see an error described here: https://github.com/cmd-ntrf/jupyter-lmod/issues/14
