### ISSUE TITLE
Feature request: add support for module (use|unsuse)

### ISSUE THREAD

**Issue by kelseymh** [cmd-ntrf/jupyter-lmod#21]
Howdy!  I'm working on a request for the Texas A&M HPRC to adopt this plugin for their OpenOnDemand Jupyter Portal.  It would allow the members of my group to load our experiment-specific modules into Jupyter, without the HPRC admins having to frequently update their OnDemand Portal page with new versions of our modules.

Does this plugin support extending MODULEPATH (i.e., `module use`) as part of the interactive Jupyter session?  I didn't notice that as part of the two demo animations on your README page.

**Comment by cmd-ntrf** [comment]
Hi!

Not in its current form, no.

The subcommands currently supported by the REST API are listed here:
https://github.com/cmd-ntrf/jupyter-lmod/blob/master/jupyterlmod/handler.py#L11

**Comment by kelseymh** [comment]
Thank you!  From that code, does that mean it would be as simple as adding
```
"use" : lmod.use
```
to the above code, and then
```
use = partial(module, 'use')
```
to [lmod/__init__.py](https://github.com/cmd-ntrf/jupyter-lmod/blob/ba771d14e88fa903ba3e6c879f54c10a4fbeddb7/lmod/__init__.py#L120)?

**Comment by cmd-ntrf** [comment]
From the REST API standpoint, yes. 

However we would also need a UI to retrieve the path to add from the user, unless you're good with adding a path with curl.

**Comment by kelseymh** [comment]
Ah, I see your point -- you need a way for the user to supply the path they want to add.  

I'm slowing getting my Python skills up to speed (mostly by way of EasyBuild bug fixes and adding features).  If we can get this installed at TAMU HPRC, I can take a look and see if I can get a `module use` to work.

**Comment by cmd-ntrf** [comment]
Exactly.

Let me edit your title to make this a feature request issue and I'll see what I can do in the coming weeks.

**Comment by cmd-ntrf** [comment]
Are you planning to use Jupyter Notebook or JupyterLab?

**Comment by kelseymh** [comment]
We've been using Jupyter Notebook on TAMU HPRC, because that was the only way we could have the OnDemand interface load our own module.  Some of the other sites we use work with JupyterLab and we load our code via a kernel.json file.  From my perspective, I don't care which way we go, as long as I and my collaborators can do our analysis :-)

**Comment by cmd-ntrf** [comment]
Quick update : I am correctly working on the version 2 of the jupyter-lmod API, and it will support use and unuse.
The API implementation is completed and available in this PR : https://github.com/cmd-ntrf/jupyter-lmod/pull/23.

I am currently working on the UI for use/unuse in the classic Jupyter Notebook UI.

**Comment by cmd-ntrf** [comment]
UI for use/unuse is implemented in Jupyter classic interface. There is a quick overview of what it looks like in the upcoming jupyter-lmod v2 demo gif available here: https://camo.githubusercontent.com/61b200abcb5795caf861d299c0c06175f78e6dd3/68747470733a2f2f692e696d6775722e636f6d2f704b31513567472e676966

**Comment by cmd-ntrf** [comment]
The feature is now included in jupyter-lmod 2.0.0b0. An non-beta release will be published next week.

**Comment by kelseymh** [comment]
Thank you!  When the non-beta release comes out, I'll ask the Texas A&M HPRC folks if they can install it with their Jupyter notebook server.
