### ISSUE TITLE
Execute command in lmod file not executed

### ISSUE THREAD

**Issue by dr-br** [cmd-ntrf/jupyter-lmod#24]
When I load a module via lmod plugin, an execute statement inside the lmod file is not executed. When I do module load manually, the execute command is executed.
Extract of my lua file:
```
...
execute{cmd="julia -E 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'", modeA={"load"}}
...
 ```
Is this my fault or is this an issue with lmod plugin?

Thanks a lot!

**Comment by cmd-ntrf** [comment]
The answer is unfortunately : neither.

jupyter-lmod uses lmod Python interface to execute module related actions. I am guessing the Python interface of Lmod does not support the execute command.

You can this yourself - run the following command followed by the name of your module in a terminal : 
```$LMOD_CMD python load your_module```

This will output the Python code jupyter-lmod executes when loading your module. If there is no mention of executing a command in that code, it will confirm Lmod does not support `execute` with its Python interface.

**Comment by dr-br** [comment]
Thanks for the reply.
