### ISSUE TITLE
`npm install` fails since jupyterlab 3.0 is released

### ISSUE THREAD

**Issue by jhgoebbert** [cmd-ntrf/jupyter-lmod#35]
`npm install` fails since jupyterlab 3.0 is released on the 24th of Dezember
because `jupyter-lmod/jupyterlab/packages.json` has the line
`"@jupyterlab/application": ">=2.0.0",` [#34](https://github.com/cmd-ntrf/jupyter-lmod/blob/master/jupyterlab/package.json#L34)
which also allows the new but incompatable version 3.0 of `@jupyterlab/application`.

For me it package.json with
```
...
  "dependencies": {
    "@jupyterlab/application": "^2.0.0",
    "@jupyterlab/apputils": "^2.1.0",
    "@jupyterlab/launcher": "^2.1.0"
  },
  "devDependencies": {
    "@types/react": "^16.9.16",
    "rimraf": "~2.6.2",
    "typescript": "~3.7.3"
  },
...
```

**Comment by cmd-ntrf** [comment]
Can you provide the error you obtained?

I just created a clean virtual environment with Python 3.9, jupyterlab 3.0.1 and after running 
```
pip install jupyterlmod
jupyter labextension install jupyter-lmod
```

I have not seen any error from npm.

**Comment by cmd-ntrf** [comment]
In my preceding comment:
```
jupyter labextension install jupyter-lmod
```
does not return error, but it also did not install the latest version of jupyter-lmod (0.8.0) but the version 0.5.0 which is not compatible with the Python server extension of jupyter-lmod 2.0.

**Comment by cmd-ntrf** [comment]
Fixed in https://github.com/cmd-ntrf/jupyter-lmod/commit/9ddb49d5f3cc6ddc196f5e1c597f2e1b76af7d2d and on npm with jupyterlab-lmod 0.8.1.

The UI with jupyterlab 3.0 is a bit glitchy, but it appears to work nonetheless. I will create another issue to track this.
