### ISSUE TITLE
Improve UI compatibility with jupyterlab 3.0

### ISSUE THREAD

**Issue by cmd-ntrf** [cmd-ntrf/jupyter-lmod#36]
The load/unload buttons do not show up in jupyterlab 3.0 as they did in 2.0.

This should be investigated and fixed.

**Comment by jhgoebbert** [comment]
This screenshots shall just show this effect.  
But the buttons are working.
![grafik](https://user-images.githubusercontent.com/9266792/129963564-14048166-c0ef-4914-9458-8afd52b20dcc.png)

![grafik](https://user-images.githubusercontent.com/9266792/129963906-e479b9a3-370b-4feb-9d89-60e7b9496347.png)

**Comment by carstenbauer** [comment]
We'd like to upgrade to JupyterLab 3.x but this is holding us back. Any efforts / plans to fix this any time soon? Otherwise we might also take a stab at fixing it ourselves.

**Comment by cmd-ntrf** [comment]
@guimou any chance you have a fix ready for a PR?

**Comment by guimou** [comment]
@cmd-ntrf Yes and know because I made the required changes in my fork, then added some more modifications (like the "featured modules" section. But I can have a look a this later today. PR by the end of the day.

**Comment by carstenbauer** [comment]
@guimou That'd be awesome!

**Comment by guimou** [comment]
Just to make sure before putting any time, is that the look you want? https://youtu.be/0ZhKZRYHwSg?t=365

**Comment by cmd-ntrf** [comment]
Yes.

**Comment by cmd-ntrf** [comment]
@guimou PR #43 has been merged and released in jupyterlab-lmod 0.8.2.
This fixes the UI compatibility.
