### ISSUE TITLE
How to Modify/Remove created collections on jupyter-lmod.

### ISSUE THREAD

**Issue by zainul1114** [cmd-ntrf/jupyter-lmod#38]
Hi Team,

How to Modify/Remove created collections on jupyter-lmod.

Regards,
Zain

**Comment by cmd-ntrf** [comment]
Hi,

There is no user interface in jupyter-lmod currently to do this.. To remove the collections, you will have to use the lmod cli.

I will add this to the list of requested features and implemented it when time allows.
