### ISSUE TITLE
How to load User-specific/shared/custom modules using jupyter-lmod

### ISSUE THREAD

**Issue by zainul1114** [cmd-ntrf/jupyter-lmod#39]
Hi,

Please help me to load User-specific/shared/custom modules using jupyter-lmod
My scenario is like below
```
[zain@master ~]$ module avail

------------------------------------------------------------------------ /opt/privatemodules ---------------------------------------------
   gcc8.3.0    intelpython3.7.7    mpich3.3    openmpi4.0.0    python3.7.6

--------------------------------------------------------------- /usr/local/lmod/lmod/modulefiles/Core ---------------------------------
   lmod    settarg    use.own

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

[zain@master ~]$
```

and i am loading this using **module use /opt/privatemodules** command from command line.
```
[zain@master ~]$ echo $MODULEPATH
/opt/privatemodules:/usr/local/modulefiles/Linux:/usr/local/modulefiles/Core:/usr/local/lmod/lmod/modulefiles/Core
[zain@master ~]$
```
i am able to view only default modules on my Jupyterhub.
![image](https://user-images.githubusercontent.com/31759122/111075129-7bea8180-850c-11eb-9b3e-5622093c213b.png)

Regards,
Zain

**Comment by mawigh** [comment]
The environment in the shell (via SSH) can be very different from what JupyterLab or Jupyter Notebook sees.
Open a Jupyter notebook and start a python kernel. Then you can have a look at $MODULEPATH.

How are you try to extend $MODULEPATH? Inside your Shell rc?
