### ISSUE TITLE
path_info new in jupyter-server-proxy

### ISSUE THREAD

**Issue by jhgoebbert** [cmd-ntrf/jupyter-lmod#42]
`jupyter-server-proxy` has introduced `path_info` as a new possibility to modify the url by a proxy-server.
[const url = PageConfig.getBaseUrl() + server_process.launcher_entry.path_info;](https://github.com/jupyterhub/jupyter-server-proxy/blob/master/jupyterlab-server-proxy/src/index.ts#L83 )

With the upcoming new version of jupyter-server-proxy this is also needed to be added to jupyter-lmod here:
[const url = PageConfig.getBaseUrl() + server_process.name + '/';](https://github.com/cmd-ntrf/jupyter-lmod/blob/master/jupyterlab/src/index.ts#L247)

**Comment by cmd-ntrf** [comment]
Do I understand correctly that this has yet been released ?
When it is released, should we configure a minimum version requirement for jupyter-server-proxy?

**Comment by jhgoebbert** [comment]
Right now this is merged to master of jupyter-server-proxy but not yet released in a new version.    
With an upcoming new version of jupyter-server-proxy jupyter-lmod would need to make a difference here.  
(I am probably too early with this issue, sorry)

**Comment by cmd-ntrf** [comment]
It's never too early to prevent changes from breaking a package :).
