### ISSUE TITLE
clarify steps for jupyterlab setup

### ISSUE THREAD

**Issue by michaelkarlcoleman** [cmd-ntrf/jupyter-lmod#7]
Hi,

I'm a bit fuzzy on which of these commands are necessary to get this working for just a modern jupyter lab setup.  (That is, I don't care about the old-style notebook interface.)  Clearly the `pip install` has to happen, and one would think the final `jupyter labextension install`.  But which (if any) of the other commands are necessary?

**Comment by michaelkarlcoleman** [comment]
Answering my own question, it appears that all of the commands must be run.

Also, if installed by `conda`, it's possible that conda package `nodejs` may also need to be installed, in order to install Jupyter extensions.

There's useful doc [here](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html).

**Comment by cmd-ntrf** [comment]
Release 1.7.4 reduces the amount of install steps for JupyterLab to two.

Let me know if it helps.
